import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import Layout from "@/components/auth/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Layout>
          {children}
          <Toaster expand visibleToasts={2} duration={1000} />
        </Layout>
      </body>
    </html>
  );
}
